import { MDXRemote } from "next-mdx-remote/rsc";
import {
  TitleSlide,
  GiantText,
  Quote,
  ImageText,
  BulletBuild,
  PromptAnimation,
  StatCounter,
  Comparison,
  ComparisonColumn,
  CodeReveal,
  VideoEmbed,
  HeroImage,
  LayeredText,
  ImageBleed,
  Collage,
  SideScrollList,
  NumberedReveal,
  Timeline,
  TimelineEvent,
  GiantScroll,
  LayeredScroll,
  VideoBackground,
  ParticleField,
  LoadingSlide,
  SlideshowMorph,
  PollQuestion,
  Callout,
  SectionDivider,
  PictureQuote,
  Reflection,
  VoiceCollage,
  EmotionRow,
  BeforeAfter,
  Outro,
  StatCompare,
  Passage,
  MapPins,
  VideoChapters,
  HotspotImage,
  AiConversation,
  ChatPreview,
  BrandIntro,
  BigStat,
  MetricGrid,
  TierStack,
  SpotlightContrast,
  SpotlightCard,
  TeamIntro,
  TeamMember,
  SpeakerIntro,
  AiArHero,
  AiArMedia,
  AiArLabel,
  RealOrFake,
  PromptWindow,
  AiKanVara,
  AiHyperobject,
  NamedPortrait,
  FigureQuote,
  ErrorSlide,
  FullscreenVideo,
  SamrLadder,
  PromptHero,
  ChatHero,
  InputHero,
  CodeGeneration,
  Manifesto,
  EditorialHero,
  ProcessChain,
  ThreeUp,
  StudentVoices,
  HeroStatement,
  TwoPaths,
  StatsTriptych,
  GrowingStatement,
  ChatFullscreen,
  VibeCoding,
  StarterSentences,
  Bollplank,
  BloomComparison,
  ThreeActs,
  Pitfall,
  PromptPrinciples,
  AgentCatalog,
  ExampleGrid,
  LixPanels,
  TranslationDemo,
  QuizDemo,
  VoiceFeedback,
  RotatingStatement,
  ChatSplit,
  EditorialQuote,
  HookStatement,
  RevealList,
  UCurveChart,
  NoviceDilemma,
  LivePoll,
  TriadStatement,
  TwoSides,
  EvidenceConstellation,
  FrictionMap,
  StrategySpectrum,
  LensIntro,
  DualAffordance,
  SAMRSpectrum,
  AcronymList,
  BloomPyramid,
  JagAIJagFlow,
  LensApplication,
  BeforeAfterPhases,
  ProcessLogPreview,
  ContractMockup,
  TimeHorizons,
  FloatingImage,
  FloatingVideo,
  SlideWithOverlays,
  RoleConstellation,
  SOLOGraph,
  NegotiationStory,
  ParallaxTimeline,
  JaggedFrontier,
  FloatingChat,
  NarrativeFrames,
  DimensionMap,
  BigDefinition,
  Denials,
  PromptToImage,
  WeirdReveal,
  WeirdSummary,
  BiasCode,
  DesignChoices,
  LiveEmbed,
  DarkPatternsApp,
  QuoteWall,
  FloatingPills,
  FloatingPhone,
  VoiceReveal,
  PowerStack,
  InfluenceChain,
  CaseGrid,
  MediaCarousel,
  MandateMap,
  HumanOnlyTriad,
  PrincipleStack,
  ZoneShift,
  WithAboutAgainstThrough,
  MirrorReveal,
  BildningContrast,
  TaskBucket,
  SkillStack,
  CoreInsight,
  OccupationRadar,
  FloatingText,
  TimelineCompression,
  ParadoxStat,
  BiasShowcase,
  RapidFireIdeas,
  HopeMontage,
  TackSlide,
  NextTokenDemo,
  DataRedaction,
  PrivacyDecree,
  LiveReflection,
  InvisibleChildPatterns,
} from "@/templates";
import { Slide } from "./Slide";
import { SlideViewer } from "./SlideViewer";
import { extractNotes } from "@/lib/extract-notes";
import { extractSlideMetas } from "@/lib/extract-slide-types";
import { extractMediaUrls } from "@/lib/extract-media-urls";
import { preprocessOverlaysForPresenter } from "@/lib/mdx-parser";
import { getTheme, themeToCssVars } from "@/themes";
import { PresentationPreloader } from "./PresentationPreloader";
import type { BrandWatermark } from "@/lib/types";

interface PresentationRendererProps {
  source: string;
  slug?: string;
  theme?: string;
  title?: string;
  brand?: BrandWatermark;
  ambient?: boolean | string;
}

// Notes: <Notes>...</Notes> blocks parsas ut innan MDX-rendering
// (se extractNotes). De finns inte kvar i MDX-källkoden när den når MDXRemote.
const mdxComponents = {
  Slide,
  TitleSlide,
  GiantText,
  Quote,
  ImageText,
  BulletBuild,
  PromptAnimation,
  StatCounter,
  Comparison,
  ComparisonColumn,
  CodeReveal,
  VideoEmbed,
  HeroImage,
  LayeredText,
  ImageBleed,
  Collage,
  SideScrollList,
  NumberedReveal,
  Timeline,
  TimelineEvent,
  GiantScroll,
  LayeredScroll,
  VideoBackground,
  ParticleField,
  LoadingSlide,
  SlideshowMorph,
  PollQuestion,
  Callout,
  SectionDivider,
  PictureQuote,
  Reflection,
  VoiceCollage,
  EmotionRow,
  BeforeAfter,
  Outro,
  StatCompare,
  Passage,
  MapPins,
  VideoChapters,
  HotspotImage,
  AiConversation,
  ChatPreview,
  BrandIntro,
  BigStat,
  MetricGrid,
  TierStack,
  SpotlightContrast,
  SpotlightCard,
  TeamIntro,
  TeamMember,
  SpeakerIntro,
  AiArHero,
  AiArMedia,
  AiArLabel,
  RealOrFake,
  PromptWindow,
  AiKanVara,
  AiHyperobject,
  NamedPortrait,
  FigureQuote,
  ErrorSlide,
  FullscreenVideo,
  SamrLadder,
  PromptHero,
  ChatHero,
  InputHero,
  CodeGeneration,
  Manifesto,
  EditorialHero,
  ProcessChain,
  ThreeUp,
  StudentVoices,
  HeroStatement,
  TwoPaths,
  StatsTriptych,
  GrowingStatement,
  ChatFullscreen,
  VibeCoding,
  StarterSentences,
  Bollplank,
  BloomComparison,
  ThreeActs,
  Pitfall,
  PromptPrinciples,
  AgentCatalog,
  ExampleGrid,
  LixPanels,
  TranslationDemo,
  QuizDemo,
  VoiceFeedback,
  RotatingStatement,
  ChatSplit,
  EditorialQuote,
  HookStatement,
  RevealList,
  UCurveChart,
  NoviceDilemma,
  LivePoll,
  TriadStatement,
  TwoSides,
  EvidenceConstellation,
  FrictionMap,
  StrategySpectrum,
  LensIntro,
  DualAffordance,
  SAMRSpectrum,
  AcronymList,
  BloomPyramid,
  JagAIJagFlow,
  LensApplication,
  BeforeAfterPhases,
  ProcessLogPreview,
  ContractMockup,
  TimeHorizons,
  FloatingImage,
  FloatingVideo,
  SlideWithOverlays,
  RoleConstellation,
  SOLOGraph,
  NegotiationStory,
  ParallaxTimeline,
  JaggedFrontier,
  FloatingChat,
  NarrativeFrames,
  DimensionMap,
  BigDefinition,
  Denials,
  PromptToImage,
  WeirdReveal,
  WeirdSummary,
  BiasCode,
  DesignChoices,
  LiveEmbed,
  DarkPatternsApp,
  QuoteWall,
  FloatingPills,
  FloatingPhone,
  VoiceReveal,
  PowerStack,
  InfluenceChain,
  CaseGrid,
  MediaCarousel,
  MandateMap,
  HumanOnlyTriad,
  PrincipleStack,
  ZoneShift,
  WithAboutAgainstThrough,
  MirrorReveal,
  BildningContrast,
  TaskBucket,
  SkillStack,
  CoreInsight,
  OccupationRadar,
  FloatingText,
  TimelineCompression,
  ParadoxStat,
  BiasShowcase,
  RapidFireIdeas,
  HopeMontage,
  TackSlide,
  NextTokenDemo,
  DataRedaction,
  PrivacyDecree,
  LiveReflection,
  InvisibleChildPatterns,
};

export async function PresentationRenderer({ source, slug, theme, title, brand, ambient }: PresentationRendererProps) {
  const { content, notes } = extractNotes(source);
  // Wrap slides med overlays (FloatingImage etc.) i SlideWithOverlays så de
  // renderas tillsammans med sin parent-template istället för som egen slide.
  const processedContent = preprocessOverlaysForPresenter(content);
  const slideMetas = extractSlideMetas(processedContent);
  // Samla alla media-URL:er för preload (server-side för att undvika hydration-mismatch).
  const mediaUrls = extractMediaUrls(processedContent);
  const themeTokens = getTheme(theme);
  const cssVars = themeToCssVars(themeTokens);

  return (
    <div
      style={cssVars as React.CSSProperties}
      data-ornament={themeTokens.ornamentStyle}
      data-theme={theme ?? "default"}
      className="h-screen w-screen"
    >
      <PresentationPreloader
        slug={slug ?? "unknown"}
        title={title ?? slug ?? "Presentation"}
        mediaUrls={mediaUrls}
      >
        <SlideViewer
          notes={notes}
          slideMetas={slideMetas}
          slug={slug}
          theme={theme ?? "default"}
          title={title}
          brand={brand}
          ambient={ambient}
        >
          <MDXRemote source={processedContent} components={mdxComponents} />
        </SlideViewer>
      </PresentationPreloader>
    </div>
  );
}
